### ISSUE TITLE
This really needs a Chrome app

### ISSUE THREAD

**Issue by nashv** [KodeKraftwerk/reepio#26]
Browser tabs are dicy. One misclick and file transfer can be broken. A chrome/native app is much better because it can be left on to complete transfers.

This is should be relatively simple using node-webkit/chrome-embedded-framework etc. In fact, I just loaded up the URL with node-webkit and it seems to work fine. Do think about a more app like interface.

**Comment by korve** [comment]
This is actually a great idea. We will look into this.
