### ISSUE TITLE
how to get vagrant box chef/debian-7.4

### ISSUE THREAD

**Issue by zjgooddream** [KodeKraftwerk/reepio#31]
hi, 
i search  "chef/debian-7.4" from  https://atlas.hashicorp.com/search, and i find https://vagrantcloud.com/woss/boxes/debian-7.4-chef

then, i try to "vagrant add box woss/debian-7.4-chef  https://vagrantcloud.com/woss/boxes/debian-7.4-chef" but it returns "The requested URL returned error: 404 Not Found"

so i don't know where to get vagran box "chef/debian-7.4"

**Comment by korve** [comment]
It seems the box does not exist anymore. I will try to update the Vagrantfile.

**Comment by korve** [comment]
Ok, c8737cb44e27b0d8198c365e3c09b1e3abb8d240 should fix it.
