### ISSUE TITLE
Create a link for multiple files

### ISSUE THREAD

**Issue by korve** [KodeKraftwerk/reepio#32]
When dropping multiple files a single link should enable the user to download all files at once.

**Comment by Pawtiko** [comment]
I'm glad to see this feature is planned. It would be very useful!
If I might make a suggestion, this could be done by using something like https://gildas-lormeau.github.io/zip.js/ or https://stuk.github.io/jszip/ to zip multiple files into one before sending them.

**Comment by korve** [comment]
You can't drop folders with it tough, can you? But selecting multiple files and putting them into one file seems like a great idea...

**Comment by maxpavlov** [comment]
@korve How come this was closed? Did it get implemented? Or you just dropped the plans to implement this all together?
