### ISSUE TITLE
lack of some js files

### ISSUE THREAD

**Issue by zjgooddream** [KodeKraftwerk/reepio#33]
sorry, after update the vagrantfile, i got the vagrant box, but when i run 'npm start' and open 'http://192.168.0.120:8080/', there are some errors, like this:

GET /js/socialshareprivacy/socialshareprivacy.css" Error (404): "Not found"
GET /bower_components/jquery/dist/jquery.js" Error (404): "Not found"
GET /bower_components/threejs/build/three.js" Error (404): "Not found
GET /bower_components/bootstrap/dist/js/bootstrap.js" Error (404): "Not found"
GET /bower_components/jquery/dist/jquery.js" Error (404): "Not found
GET /bower_components/threejs/build/three.js" Error (404): "Not found
GET /bower_components/bootstrap/dist/js/bootstrap.js" Error (404): "Not found"

**Comment by korve** [comment]
Hey, i've streamlined the build process with 5ba168d2af71ddfa549bc5109f4135d43dd28126. Everything should now work as documented.
