### ISSUE TITLE
Stuck on generating url

### ISSUE THREAD

**Issue by danielrnrz** [KodeKraftwerk/reepio#42]
Hello,

I've successfully launched the reepio server and reepio, I can access to the webpage on port 9001 by default but when I try to add a file, it does not generate any url. Does anybody got this problem too ?

![image](https://cloud.githubusercontent.com/assets/4125310/22184668/e8133110-e0d6-11e6-977e-ad8a153f91d5.png)

**Comment by korve** [comment]
@danielrnrz You need to start up a peering server (https://github.com/KodeKraftwerk/reepio-peering-server) to be able to establish a connection.

**Comment by danielrnrz** [comment]
Hello, 

That's what I did. In fact, if I add another file, it generates the url but not for the first file.

**Comment by gabsoftware** [comment]
The same is true for the website reep.io!

**Comment by korve** [comment]
Closed because we had some peering server issues.
