### ISSUE TITLE
Reep.io cannot generate URL

### ISSUE THREAD

**Issue by Commander-Zal** [KodeKraftwerk/reepio#49]
When I attempt to use Reep.io, after I choose a file to upload, the text 'Generating URL..." appears but it never seems to actually finish generating said URL.

This occurs on Firefox 60.0.1, if that helps. :)

**Comment by korve** [comment]
The issue has been resolved.

**Comment by Commander-Zal** [comment]
Thank you very much! ^_^

**Comment by Kabouik** [comment]
I am having the same issue since several months on reep.io, with both Chrome and Firefox. They are both up to date and I'm using Linux, but don't think it's relevant.

Would there be any command line tool to to access the reep.io service from the terminal and share a file, by any chance?
